version: "3.3"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  builder:
    depends_on:
      - mysqldb
    dockerfile: Dockerfile.build
    context: ./
    volumes:
      - data:/opt
  prod:
    image: tomcat:9.0.8-jre8-alpine
    volumes:
      - data:/usr/local/tomcat/webapps
    depends_on:
      - builder
    ports:
      - $WEB_PORT:$WEB_PORT
  
volumes:
  data:
  db:
